### ISSUE TITLE
수정사항 2015.04.08 021:10

### ISSUE THREAD

**Issue by ghost** [whitelog/r-con-2015#2]
프로그램 페이지에서 상단 두 줄 색 제거
프로그램 시간 표시 다음 세로줄 추가
상단 배경 이미지 삽입
메인 페이지 하단 이미지 추가

**Comment by ghost** [comment]
미안한데.. 등록에도 색을 넣은 게 좋을 듯..

**Comment by hwanghakbeom** [comment]
등록에 색상 추가
