### ISSUE TITLE
발표자 삭제

### ISSUE THREAD

**Issue by ghost** [whitelog/r-con-2015#4]
1. 스케줄에 SKT는 두 번째 키노트 하나만 남겨 놓고,
2. 미정이는 미정으로 변경
3. 마지막 세션에 서민구씨 관련 내용은 "미정"으로 변경
4. 이메일 내용으로 스케줄에는
   발표제목
   이름/소속
   의 내용으로 정보 추가하고 스폰서 내용 추가

**Comment by hwanghakbeom** [comment]
스케줄에 SKT는 두 번째 키노트 하나만 남겨 놓고,
미정이는 미정으로 변경
마지막 세션에 서민구씨 관련 내용은 "미정"으로 변경
이메일 내용으로 스케줄에는 발표제목 이름/소속 의 내용으로 정보 추가하고 스폰서 내용 추가

**Comment by ghost** [comment]
1. 키노트 미정이를 미정으로 변경한게 아니라 아예 내용을 삭제한 듯? 삭제하지 말고 미정으로 표시
2. 오후 세션 표시 할 때 섹션 간 세로줄 삽입
3. 오후 세션에 제목/발표자 정보를 표시할 때 이 둘을 하나의 컬럼에 넣다보니 제목의 길이에 따라 발표자 정보의 위치가 다르게 보여 좋지 않음(오후 첫번째 시간대의 기상청과 그루터 내용 표현된 것 비교). 그래서 제목과 발표자 정보를 두 개의 행으로 하고 가로줄을 표시하지 않아 하나의 셀처럼 보이게 하는 것이 좋아보임. 트랙별 세로줄은 넣고..
4. 스피커스 페이지에 기상청 김승욱씨 발표 내용 수정(이메일 내용 참고)
